blank_issues_enabled: false
contact_links:
  - name: Nous rejoindre sur siphonium pour jouer avec nous oupour nous faire des demandes
    about: Veuillez ne pas ouvrir d'issue autre que pour signaler des bugs
