name: Launcher Build

on:
  push:
    branches: [ master ] # Workflow déclenché par des pushs sur master
  workflow_dispatch: # Ajout pour permettre un lancement manuel

jobs:
  build-launcher:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install Dependencies
        run: npm ci
        shell: bash

      - name: Build
        run: npm run build
        shell: bash

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: siphonium-build
          path: ./siphonium-build/*
